version: "3.9"
services:
  backend:
    build: ./backend
    container_name: map-scraper-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      - MONGO_DB_NAME=maps_scraper   

  frontend:
    build: ./frontend
    container_name: map-scraper-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
