version: "3.9"
services:
  mongo:
    image: mongo:7.0
    container_name: map-scraper-mongo
    ports:
      - "27018:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend
    container_name: map-scraper-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=maps_scraper
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    command: ["python", "app.py"]

  frontend:
    image: node:22-alpine
    container_name: map-scraper-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true   
      - CHOKIDAR_INTERVAL=300  
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
